# Generated by Django 5.0.6 on 2025-11-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('template', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('verhoeff_score', models.FloatField(blank=True, null=True)),
                ('layout_score', models.FloatField(blank=True, null=True)),
                ('text_score', models.FloatField(blank=True, null=True)),
                ('copy_move_score', models.FloatField(blank=True, null=True)),
                ('metadata_score', models.FloatField(blank=True, null=True)),
                ('ela_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
